[versions]
kotlin = "2.0.21"
paper = "1.21.11-R0.1-SNAPSHOT"
paperweight = "2.0.0-beta.17"
shadow = "9.0.0-beta4"
pluginyml = "0.7.1"
adventure = "4.25.0"
apache-commons-text = "1.11.0"
buildconfig = "5.5.1"
commandapi = "11.1.0"
snakeyaml = "2.2"
exposed = "0.61.0"
hikaricp = "6.2.1"
junit = "5.11.1"
h2 = "2.3.232"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-text-logger = { module = "net.kyori:adventure-text-logger-slf4j", version.ref = "adventure" }
adventure-text-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-text-serializer-legacy = { module = "net.kyori:adventure-text-serializer-legacy", version.ref = "adventure" }
adventure-text-serializer-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }
adventure-text-serializer-ansi = { module = "net.kyori:adventure-text-serializer-ansi", version.ref = "adventure" }
apache-commons-text = { module = "org.apache.commons:commons-text", version.ref = "apache-commons-text" }
commandapi-core = { module = "dev.jorel:commandapi-paper-core", version.ref = "commandapi" }
commandapi-kotlin = { module = "dev.jorel:commandapi-kotlin-paper", version.ref = "commandapi" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }

jetbrains-exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
jetbrains-exposed-migration = { module = "org.jetbrains.exposed:exposed-migration", version.ref = "exposed" }
jetbrains-exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
jetbrains-exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }

snakeyaml = { module = "org.yaml:snakeyaml", version.ref = "snakeyaml" }

junit = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
pluginyml-paper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginyml" }